import { useMemo, useState } from 'react'
import { useOutletContext } from 'react-router-dom'
import HeatGridMap from '../../components/maps/HeatGridMap'
import AreaSearchSuggestions from '../../components/shared/AreaSearchSuggestions'
import Slider from '../../components/ui/Slider'
import Badge from '../../components/ui/Badge'

export default function HeatMap(){
 const {globalSearch,setGlobalSearch}=useOutletContext();const [layer,setLayer]=useState('lst');const [season,setSeason]=useState('Dry season');const [min,setMin]=useState(24);const [selected,setSelected]=useState(null)
 const layers=[['lst','Land Surface Temperature'],['ndvi','NDVI — Vegetation'],['ndbi','NDBI — Built-up'],['lst','Green Space Mask'],['ndvi','Adjacency (NDVI_ADJ / NDBI_ADJ)']]
 return <div><AreaSearchSuggestions query={globalSearch} onSelect={setGlobalSearch}/><div className="mb-5"><h1 className="text-[24px] font-bold">Heat Map</h1><p className="text-[11px] text-slate-500">210 m grid · 2,194 zones · prototype GIS visualization</p></div><div className="grid gap-5 xl:grid-cols-[300px_1fr]">
  <div className="card-pad self-start"><h2 className="section-title">Layers & filters</h2><label className="mt-4 block text-[10px] font-semibold uppercase text-slate-500">Map layer<select value={layer} onChange={e=>setLayer(e.target.value)} className="control mt-2">{layers.map(([v,l],i)=><option key={i} value={v}>{l}</option>)}</select></label><label className="mt-4 block text-[10px] font-semibold uppercase text-slate-500">Season<select value={season} onChange={e=>setSeason(e.target.value)} className="control mt-2"><option>Dry season</option><option>Wet season</option></select></label><div className="mt-5"><Slider label="Minimum LST" value={min} onChange={setMin} min={24} max={40} suffix="°C"/></div><div className="mt-5"><div className="text-[10px] font-semibold uppercase text-slate-500">Thermal legend</div><div className="mt-3 space-y-2">{[['#2B6CB0','< 28°C'],['#4A99B8','28 – 31.5°C'],['#D9A441','31.5 – 35°C'],['#EA7C2B','35 – 37.5°C'],['#E0472B','> 37.5°C']].map(([c,t])=><div className="flex items-center gap-2 text-[11px]" key={t}><span className="h-3 w-6 rounded" style={{background:c}}/>{t}</div>)}</div></div><div className="mt-5 data-note">LST is displayed separately for wet and dry season composites to demonstrate how seasonal variation can be considered. Values are simulated.</div></div>
  <div className="card-pad"><div className="mb-3 flex items-center justify-between"><div><h2 className="section-title">Land Surface Temperature</h2><p className="text-[11px] text-slate-500">{season} composite</p></div><Badge variant="amber">Prototype demo data</Badge></div><HeatGridMap mode={layer} height={610} minLst={min} selectedId={selected?.zoneId} onSelect={setSelected} highlightArea={globalSearch}/>{selected&&<div className="mt-4 grid gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-2 lg:grid-cols-4"><div><div className="text-[10px] text-slate-400">Zone</div><b>{selected.zoneId} · {selected.areaName}</b></div><div><div className="text-[10px] text-slate-400">LST</div><b>{selected.lst2025}°C</b></div><div><div className="text-[10px] text-slate-400">NDVI / NDBI</div><b>{selected.ndvi} / {selected.ndbi}</b></div><div><div className="text-[10px] text-slate-400">LCZ</div><b className="text-[11px]">{selected.lcz}</b></div><div><div className="text-[10px] text-slate-400">NDWI / EVI / Albedo</div><b>{selected.ndwi} / {selected.evi} / {selected.albedo}</b></div><div><div className="text-[10px] text-slate-400">Building / road density</div><b>{selected.buildingDensity} / {selected.roadDensity}</b></div><div><div className="text-[10px] text-slate-400">Distance to water / road</div><b>{selected.distanceToWater}m / {selected.distanceToRoad}m</b></div><div><div className="text-[10px] text-slate-400">NightLights / Trend</div><b>{selected.nightLights} · {selected.trend}</b></div></div>}</div>
 </div></div>
}
