import { useState } from 'react'
import { Bell, Database, Moon, Sun, UserRound } from 'lucide-react'
import Toggle from '../../components/ui/Toggle'
import Button from '../../components/ui/Button'
import { useApp } from '../../contexts/AppContext'

export default function Settings(){
 const {profile,showToast}=useApp();const [notices,setNotices]=useState(true);const [compact,setCompact]=useState(false);const [theme,setTheme]=useState('Light')
 return <div><div className="mb-5"><h1 className="text-[24px] font-bold">Settings</h1><p className="text-[11px] text-slate-500">Prototype preferences and account settings</p></div><div className="grid gap-5 xl:grid-cols-3"><div className="card-pad"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#0F2E28] text-white"><UserRound/></div><div><div className="font-bold">{profile.name}</div><div className="text-[11px] text-slate-500">{profile.role}</div></div></div><div className="mt-5 space-y-3 text-[11px]"><div className="soft-panel"><span className="text-slate-400">Organization</span><b className="mt-1 block">{profile.organization}</b></div><div className="soft-panel"><span className="text-slate-400">Email</span><b className="mt-1 block">{profile.email}</b></div></div><p className="mt-4 text-[10px] text-slate-400">Use the profile control in the top-right header to change name, role, organization, email, and photo.</p></div><div className="card-pad"><div className="flex items-center gap-2"><Bell size={18} className="text-teal-600"/><h2 className="section-title">System settings</h2></div><div className="mt-5 space-y-3"><Toggle checked={notices} onChange={setNotices} label="Enable prototype notifications"/><Toggle checked={compact} onChange={setCompact} label="Compact data tables"/></div><div className="mt-5"><div className="mb-2 text-[11px] font-semibold text-slate-600">Theme options</div><div className="grid grid-cols-2 gap-2"><button onClick={()=>setTheme('Light')} className={`rounded-xl border p-3 text-left text-xs ${theme==='Light'?'border-teal-400 bg-teal-50':'border-slate-200'}`}><Sun size={16} className="mb-2"/>Light</button><button onClick={()=>setTheme('Dark preview')} className={`rounded-xl border p-3 text-left text-xs ${theme==='Dark preview'?'border-teal-400 bg-teal-50':'border-slate-200'}`}><Moon size={16} className="mb-2"/>Dark preview</button></div></div><Button className="mt-5 w-full" onClick={()=>showToast('Settings saved for this prototype session.')}>Save settings</Button></div><div className="card-pad"><div className="flex items-center gap-2"><Database size={18} className="text-teal-600"/><h2 className="section-title">Data & model status</h2></div><div className="mt-5 space-y-3 text-[11px]"><div className="soft-panel"><span className="text-slate-400">Dataset</span><b className="mt-1 block">Local simulated data</b></div><div className="soft-panel"><span className="text-slate-400">Grid zones</span><b className="mt-1 block">2,194 generated demo records</b></div><div className="soft-panel"><span className="text-slate-400">Backend connection</span><b className="mt-1 block text-amber-700">Not connected — prototype only</b></div><div className="soft-panel"><span className="text-slate-400">Model status</span><b className="mt-1 block text-amber-700">Demo outputs — not trained/validated here</b></div></div></div></div></div>
}
