import { Database, Droplets, Leaf, Map, Ruler, ShieldCheck, Sparkles, Workflow } from 'lucide-react'
const steps=[
 ['Data collection',Database,'Use Landsat, Sentinel-2, Google Earth Pro validation images, river/canal layers, DEM, OpenStreetMap roads/buildings, and river buffer zones.'],
 ['Water boundary extraction',Droplets,'Use NDWI, MNDWI, or AWEI to identify river water boundary and active river channel.'],
 ['Vegetation & built-up feature extraction',Leaf,'Use NDVI/EVI for river-edge vegetation and NDBI/OSM data for built-up pressure.'],
 ['Riverbank & channel-change analysis',Ruler,'Compare river boundary positions across time and measure active channel-width variation using transect-style analysis.'],
 ['Buffer & encroachment analysis',Map,'Create 30 m, 50 m and 100 m river buffers to identify vegetation loss, road proximity, building density and built-up encroachment.'],
 ['Risk scoring / ML modelling',ShieldCheck,'Use GIS risk scoring, Random Forest, XGBoost, Decision Tree, SVR, or clustering methods depending on data availability.'],
 ['Feature importance & explanation',Sparkles,'Identify which factors contribute most to riverbank risk, such as vegetation loss, built-up encroachment, movement indicators, road proximity and buffer condition.'],
 ['Dashboard visualization',Workflow,'Generate river corridor change maps, movement indicators, buffer-condition maps, encroachment maps, risk zones, protection-priority maps, charts, tables and planning recommendations.']
]
export default function Methodology(){return <div><div className="mb-5"><h1 className="page-title">Methodology and research workflow</h1><p className="page-subtitle">River corridor data → Water boundary extraction → Riverbank/channel change analysis → Vegetation buffer & built-up encroachment analysis → Risk classification → Protection-priority planning dashboard</p></div><div className="card-pad"><div className="relative space-y-0">{steps.map(([title,Icon,text],i)=><div key={title} className="relative flex gap-5 pb-7 last:pb-0"><div className="relative z-10 grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#0F2E28] text-sky-300"><Icon size={20}/></div>{i<steps.length-1&&<div className="absolute left-[23px] top-12 h-full w-px bg-slate-200"/>}<div className="pt-1"><div className="text-sm font-bold text-slate-900">{i+1}. {title}</div><p className="mt-1 text-[12px] leading-5 text-slate-500">{text}</p></div></div>)}</div></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[['Erosion-like change','Planning-level spatial indicator, not an engineering erosion rate.'],['Riverbank movement indicator','Historical boundary movement used for corridor monitoring.'],['Protection-priority zones','Planning-support output combining change and pressure evidence.'],['Data confidence','Each output should communicate uncertainty and data quality.']].map(([h,t])=><div key={h} className="card-pad"><b className="text-sm">{h}</b><p className="mt-2 text-[11px] leading-5 text-slate-500">{t}</p></div>)}</div><div className="data-note mt-5">No exact engineering erosion prediction, flood-depth prediction, flood-timing prediction or legal development approval is claimed by this prototype.</div></div>}
